from django.db import models

class NetWorth(models.Model):
    liquid_money = models.FloatField()
    fds = models.FloatField()
    stocks_value = models.FloatField()
    mutual_funds = models.FloatField()
    us_stocks = models.FloatField()
    crypto = models.FloatField()
    debt_funds = models.FloatField()
    epf = models.FloatField()
    ppf = models.FloatField()
    vpf = models.FloatField()
    nps = models.FloatField()
    sukanya_samruddhi_yojna = models.FloatField()
    senior_citizen_savings_scheme = models.FloatField()
    other_government_investments = models.FloatField()
    jewellery = models.FloatField()
    sgb = models.FloatField()
    gold_etf = models.FloatField()
    digital_gold = models.FloatField()
    silver = models.FloatField()
    home_value = models.FloatField()
    land_value = models.FloatField()
    reits = models.FloatField()
    liabilities = models.FloatField()
